# Generated by Django 6.0.4 on 2026-04-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite',
        ),
    ]
