# Generated by Django 6.0.4 on 2026-04-24 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
