# Generated by Django 6.0.4 on 2026-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
