# Generated by Django 6.0.4 on 2026-04-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='profiles.Follow', to='profiles.userprofile'),
        ),
    ]
