# Generated by Django 6.0.4 on 2026-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='recipe_name',
            field=models.TextField(blank=True, max_length=10, verbose_name='Nombre'),
        ),
    ]
