# Generated by Django 6.0.4 on 2026-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre'),
        ),
    ]
