# Generated by Django 6.0.4 on 2026-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_receta_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='recipes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Descripcion'),
        ),
    ]
