# Generated by Django 6.0.4 on 2026-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_alter_receta_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(upload_to='recetas_images/', verbose_name='Imagen'),
        ),
    ]
