# Generated by Django 6.0.4 on 2026-04-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_receta_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='favourite',
        ),
    ]
