# Generated by Django 6.0.4 on 2026-04-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
