# Generated by Django 6.0.4 on 2026-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0011_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredients',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ingredientes'),
        ),
    ]
