# Generated by Django 6.0.4 on 2026-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_receta_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='valoracion',
            field=models.IntegerField(default=0, verbose_name='Valoracion'),
        ),
    ]
