# Generated by Django 6.0.4 on 2026-04-30 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_receta_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='valoracion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valoracion'),
        ),
    ]
