# Generated by Django 6.0.4 on 2026-04-30 10:03

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0014_alter_receta_valoracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='valoracion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valoracion'),
        ),
        migrations.AlterUniqueTogether(
            name='receta',
            unique_together={('user', 'recipe_name')},
        ),
    ]
