# Generated by Django 6.0.4 on 2026-05-03 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0015_alter_receta_valoracion_alter_receta_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='valoracion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valoracion'),
        ),
    ]
