# Generated by Django 6.0.4 on 2026-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0016_alter_receta_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='recipes',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Descripcion'),
        ),
    ]
