# Generated by Django 6.0.4 on 2026-05-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0017_alter_receta_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='likes',
        ),
    ]
